services:
  - type: web
    name: ecommerce-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn EcommerceApi.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce-db
          property: connectionString
